### ISSUE TITLE
Migrate off of Spring HATEOAS's Provider interface

### ISSUE THREAD

**Issue by gregturn** [ingogriebsch/spring-hateoas-siren#51] opened 2020-07-29 18:48 UTC
Take a peek at https://github.com/toedter/spring-hateoas-jsonapi/pull/2, for an initial view of moving off that unnecessary interface.

@toedter is working to polish the ACTUAL solution, so stay tuned.

**Comment by ingogriebsch** [comment] 2020-07-29 21:14
Duplicate of #47

**Closed by ingogriebsch** 2020-07-29 21:14 UTC
Labels: duplicate
